version: "3"
services:
  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/sever.pid && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    volumes:
      - .:/webapp
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
  db:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp_development
    ports:
      - "3306:3306"
  web:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - tmp-data:/webapp/tmp
    depends_on:
      - app
volumes:
  tmp-data:
  log-data: